/**
 * Convert the TMX listed-companies XLSX into a structured TypeScript module
 * for OpenSEDAR. Output: src/data/allIssuers.ts
 *
 * Filters:
 *  - drops ETPs, CDRs, Closed-End Funds (not operating companies)
 *  - keeps issuers with a valid ticker + name
 *
 * Adds a `composite` flag for S&P/TSX Composite members (~230 large/mid caps).
 *
 * Output count target: ~2,500 operating-company issuers across TSX + TSXV.
 */
import XLSX from "xlsx";
import fs from "node:fs";
import path from "node:path";

const wb = XLSX.readFile("scripts/tmx_listed.xlsx");

const SKIP_SECTORS = new Set([
  "ETP",
  "CDR",
  "Closed-End Funds",
  "Structured Products",
]);

/** @typedef {{
 *  ticker: string,
 *  name: string,
 *  exchange: "TSX" | "TSXV",
 *  sector: string,
 *  subSector: string,
 *  hqProvince: string,
 *  hqCountry: string,
 *  marketCapCadMillions: number,
 *  composite: boolean,
 *  listingDate?: string,
 * }} ParsedIssuer
 */

function parseSheet(sheetName, exchange) {
  const ws = wb.Sheets[sheetName];
  const aoa = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });
  // Header is at row 9 (0-indexed). Data starts at row 10.
  const header = aoa[9];
  const colIdx = (label) =>
    header.findIndex((h) =>
      String(h).replace(/\s+/g, " ").trim().toLowerCase().startsWith(
        label.toLowerCase(),
      ),
    );
  const I = {
    name: colIdx("Name"),
    ticker: colIdx("Root"),
    marketCap: colIdx("Market Cap"),
    sector: colIdx("Sector"),
    subSector: colIdx("Sub"),
    hqProvince: colIdx("HQ\r\nLocation"),
    hqCountry: colIdx("HQ\r\nRegion"),
    // "S&P/TSX Index" column contains "Composite" as a value (not a column name).
    spIndex: header.findIndex((h) => String(h).includes("S&P/TSX Index")),
    tsx30: header.findIndex((h) => String(h).includes("TSX30")),
    listingDate: colIdx("Listing Date"),
  };

  const out = [];
  for (let i = 10; i < aoa.length; i++) {
    const row = aoa[i];
    const ticker = String(row[I.ticker] || "").trim();
    const name = String(row[I.name] || "").trim();
    const sector = String(row[I.sector] || "").trim();
    if (!ticker || !name) continue;
    if (SKIP_SECTORS.has(sector)) continue;
    const marketCapRaw = Number(row[I.marketCap]) || 0;
    const marketCapMillions = Math.round(marketCapRaw / 1_000_000);
    const spIndexCell = I.spIndex >= 0 ? String(row[I.spIndex] || "").trim() : "";
    const tsx30Cell = I.tsx30 >= 0 ? String(row[I.tsx30] || "").trim() : "";
    // "S&P/TSX Index" column contains "Composite", "60", "MidCap" etc. for index
    // members — any non-empty value means the issuer is in some S&P/TSX index.
    const isIndexMember = spIndexCell.length > 0;
    out.push({
      ticker,
      name,
      exchange,
      sector,
      subSector: String(row[I.subSector] || "").trim(),
      hqProvince: String(row[I.hqProvince] || "").trim(),
      hqCountry: String(row[I.hqCountry] || "").trim(),
      marketCapCadMillions: marketCapMillions,
      composite: isIndexMember,
      tsx30: tsx30Cell.toUpperCase() === "Y" || tsx30Cell.includes("Y"),
      listingDate: row[I.listingDate] ? String(row[I.listingDate]) : undefined,
    });
  }
  return out;
}

const tsx = parseSheet("TSX Issuers April 2026", "TSX");
const tsxv = parseSheet("TSXV Issuers April 2026", "TSXV");
const all = [...tsx, ...tsxv];

// Sort by market cap descending so top issuers are easy to slice off.
all.sort((a, b) => b.marketCapCadMillions - a.marketCapCadMillions);

console.error(
  `parsed: TSX=${tsx.length}, TSXV=${tsxv.length}, total=${all.length}, composite=${all.filter((i) => i.composite).length}`,
);
console.error(`top 5: ${all.slice(0, 5).map((i) => `${i.ticker}=$${(i.marketCapCadMillions / 1000).toFixed(1)}B`).join(", ")}`);

// Write JSON snapshot for diagnostics
fs.writeFileSync("scripts/all_issuers.json", JSON.stringify(all, null, 0));

// Write as TypeScript module
const ts = `// AUTO-GENERATED by scripts/build_issuers.mjs from TMX's April 2026 listed-issuers XLSX.
// DO NOT EDIT BY HAND — regenerate via: node scripts/build_issuers.mjs
//
// ${all.length} operating-company issuers across TSX (${tsx.length}) + TSXV (${tsxv.length}).
// ETPs, CDRs, and Closed-End Funds filtered out.

import { Issuer } from "@/lib/types";

export interface RawTmxIssuer {
  ticker: string;
  name: string;
  exchange: "TSX" | "TSXV";
  sector: string;
  subSector: string;
  hqProvince: string;
  hqCountry: string;
  marketCapCadMillions: number;
  composite: boolean;
  tsx30: boolean;
  listingDate?: string;
}

export const TMX_ISSUERS: RawTmxIssuer[] = ${JSON.stringify(all)};

export const TMX_TICKER_INDEX: Record<string, RawTmxIssuer> = (() => {
  const idx: Record<string, RawTmxIssuer> = {};
  for (const i of TMX_ISSUERS) {
    idx[i.ticker.toUpperCase()] = i;
  }
  return idx;
})();

export function getRawIssuerByTicker(ticker: string): RawTmxIssuer | undefined {
  return TMX_TICKER_INDEX[ticker.toUpperCase()];
}

/**
 * Project the raw TMX record into the demo's Issuer shape. Used as a fallback
 * for tickers that don't have a hand-curated record in src/data/issuers.ts.
 */
export function tmxToIssuer(raw: RawTmxIssuer): Issuer {
  const hq = raw.hqProvince
    ? \`\${raw.hqProvince}, \${raw.hqCountry || "Canada"}\`
    : raw.hqCountry || "—";
  return {
    ticker: raw.ticker,
    name: raw.name,
    exchange: raw.exchange,
    sector: raw.sector || "—",
    industry: raw.subSector || raw.sector || "—",
    hq,
    marketCapCadMillions: raw.marketCapCadMillions,
    blurb: \`\${raw.name} is a \${raw.sector.toLowerCase() || "Canadian"} issuer listed on \${raw.exchange} (HQ \${hq}).\`,
    // SEDAR+ doesn't support deep-link search via query params. Land users
    // on the working profile-search form; they enter the ticker manually.
    sedarProfileUrl: "https://www.sedarplus.ca/csa-party/service/create.html?targetAppCode=csa-party&service=searchIndustryParticipant",
  };
}

export const TMX_TOP_BY_MCAP: RawTmxIssuer[] = TMX_ISSUERS;
export const TMX_COMPOSITE: RawTmxIssuer[] = TMX_ISSUERS.filter((i) => i.composite);
`;

fs.writeFileSync("src/data/allIssuers.ts", ts);
console.error(`wrote src/data/allIssuers.ts (${ts.length} bytes)`);
